cloud:
  aws:
    credentials:
      access-key: AKIAY3PLHSUJCBSLMMWR
      secret-key: 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
    region:
      static: us-west-1
    stack:
      auto: false

application:
  bucket:
    name: grupo6california

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    username: grupo6dh1511@gmail.com
    password: frqvjqfdwjnxvrwv
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


server:
  port: 8080